name: accessor
description: A simple variable accessor.
version: 0.0.9
repository: https://github.com/onurmio/Accessor

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^3.0.4
  logger: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
